apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: loki-flow-for-tetragon
  namespace: kube-system
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        reserve_data: true
        parse:
          type: json
          time_key: time
          time_format:  "%iso8601"
  match:
    - select:
        labels:
          app.kubernetes.io/instance: tetragon
  localOutputRefs:
    - loki-output